### ISSUE TITLE
Starting without previous projects.json fails

### ISSUE THREAD

**Issue by mlang** [kquick/mywork#4]
Running mywork fresh without any previous projects.json file fails:

mywork: Error in $: not enough input
CallStack (from HasCallStack):
  error, called at lib/Panes/FileMgr.hs:323:21 in mywork-1.0.1.0-4AGYMzaSU3t5dVevhoSzub:Panes.FileMgr

It appears the parser fails on the empty file created.

And since there is no example projects.json anywhere around,
there is currently no real way to start the app at all.

**Comment by kquick** [comment]
Oops.  This was handled better early on, but obviously I've been focusing my efforts on my pre-existing projects file.  I've fixed this in https://github.com/kquick/mywork/commit/ea3520332654b1d22639ba9353f5f4292d8b59c8, thanks for the report.
